# Generated by Django 5.0.7 on 2026-05-17 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrainingJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('model_dir', models.CharField(blank=True, default='', max_length=400)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=32)),
                ('meta', models.TextField(blank=True, default='{}')),
                ('log', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
