import json

from django.utils import timezone

from api.models import Alert, AlertAudit, User


def score_recent_features(data_dir, model_dir):
    """Load engineered features and produce alert candidates."""
    import pandas as pd
    from api.ml_models.anomaly_ensemble import load_artifacts, score_features

    feature_path = f'{data_dir}/features.parquet'
    df = pd.read_parquet(feature_path)
    artifacts = load_artifacts(model_dir)
    scored = score_features(artifacts, df)
    return df, scored, artifacts


def create_or_update_alert(user_id, score, severity, reason, metadata=None, threshold=0.0):
    try:
        user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        # Skip creating alerts for missing users; log to stderr for debugging
        try:
            import sys
            sys.stderr.write(f"create_or_update_alert: user {user_id} does not exist, skipping.\n")
        except Exception:
            pass
        return None

    payload = json.dumps(metadata or {})
    alert = Alert.objects.create(
        user=user,
        score=score,
        severity=severity,
        reason=reason,
        metadata=payload,
        status=Alert.STATUS_NEW,
    )
    AlertAudit.objects.create(alert=alert, action='created', actor=None, note='Generated by anomaly model')
    return alert


def severity_from_score(score):
    if score >= 0.9:
        return 5
    if score >= 0.8:
        return 4
    if score >= 0.7:
        return 3
    if score >= 0.6:
        return 2
    return 1


def create_alerts_from_scores(df, scores, threshold=0.8):
    created = []
    for row, scored in zip(df.to_dict(orient='records'), scores):
        if scored['score'] < threshold and not scored['is_anomaly']:
            continue
        user_id = row['user_id']
        severity = severity_from_score(scored['score'])
        metadata = {
            'row_index': scored['row_index'],
            'iso_score': scored['iso_score'],
            'reconstruction_error': scored['reconstruction_error'],
            'date': str(row.get('date')),
        }
        reason = 'Automated anomaly detected from mood, note, and behavior signals.'
        alert = create_or_update_alert(user_id, scored['score'], severity, reason, metadata=metadata)
        if alert is not None:
            created.append(alert)
    return created


def acknowledge_alert(alert, actor, note=''):
    alert.status = Alert.STATUS_ACK
    alert.reviewed_by = actor
    alert.reviewed_at = timezone.now()
    alert.save(update_fields=['status', 'reviewed_by', 'reviewed_at'])
    AlertAudit.objects.create(alert=alert, action='acknowledged', actor=actor, note=note)
    return alert


def resolve_alert(alert, actor, note='', status=Alert.STATUS_RESOLVED):
    alert.status = status
    alert.reviewed_by = actor
    alert.reviewed_at = timezone.now()
    alert.save(update_fields=['status', 'reviewed_by', 'reviewed_at'])
    AlertAudit.objects.create(alert=alert, action=status, actor=actor, note=note)
    return alert
